#!/usr/bin/python
"""Highly divisible triangular number

   The sequence of triangle numbers is generated by adding the natural numbers.
   So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
   first ten terms would be:

   $$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \ldots$$

   Let us list the factors of the first seven triangle numbers:

        1: 1
        3: 1,3
        6: 1,2,3,6
       10: 1,2,5,10
       15: 1,3,5,15
       21: 1,3,7,21
       28: 1,2,4,7,14,28

   We can see that 28 is the first triangle number to have over five divisors.

   What is the value of the first triangle number to have over five hundred
   divisors?"""

import itertools
import eulerlib

prevQty = 1
for i in itertools.count(2):
    qty = eulerlib.product((k if p==2 else k+1) for p,k in eulerlib.factor(i+1))
    # qty == number of divisors of i+1 (or of (i+1)//2 when i+1 is even)
    if qty * prevQty > 500:
	print i*(i+1)//2
	break
    prevQty = qty
