#!/usr/bin/python
r"""Pentagon numbers

    Pentagonal numbers are generated by the formula, $P_n=n(3n-1)/2$.  The
    first ten pentagonal numbers are:

    $$1, 5, 12, 22, 35, 51, 70, 92, 117, 145, \ldots$$

    It can be seen that $P_4 + P_7 = 22 + 70 = 92 = P_8$.  However, their
    difference, $70-22 = 48$, is not pentagonal.

    Find the pair of pentagonal numbers, $P_j and P_k$, for which their sum and
    difference are pentagonal and $D = |P_k - P_j|$ is minimised; what is the
    value of $D$?"""

# Find the smallest $D = P_k + 3nk$ that is pentagonal and such that $2P_n +
# P_k + 3nk = 2P_n + D$ is pentagonal.

import heapq
import itertools
from   eulerlib import perfectSqrt

def pent(n): return n*(3*n-1) // 2

def isPent(n):
    x = perfectSqrt(1 + 24*n)
    return x is not None and (1 + x) % 6 == 0

queue = [(4, 1, 1, 1)]

while True:
    (D, Pk, k, n) = heapq.heappop(queue)
    if isPent(D) and isPent(2*pent(n) + D):
	print D
	break
    heapq.heappush(queue, (Pk + 3*(n+1)*k, Pk, k, n+1))
    if n == 1:
	Pk_1 = pent(k+1)
	heapq.heappush(queue, (Pk_1 + 3*(k+1), Pk_1, k+1, 1))
