#!/usr/bin/python
r"""Pentagonal numbers are generated by the formula, $P_n=n(3n-1)/2$.  The
    first ten pentagonal numbers are:

    $$1, 5, 12, 22, 35, 51, 70, 92, 117, 145, \ldots$$

    It can be seen that $P_4 + P_7 = 22 + 70 = 92 = P_8$.  However, their
    difference, $70-22 = 48$, is not pentagonal.

    Find the pair of pentagonal numbers, $P_j and P_k$, for which their sum and
    difference are pentagonal and $D = |P_k - P_j|$ is minimised; what is the
    value of $D$?"""

import itertools
import sys

def pentagons():
    return itertools.imap(lambda n: n*(3*n-1)//2, itertools.count(1))

pentCache = set()
maxCache = 0
(deltas, caches) = itertools.tee(pentagons(), 2)

def isPent(n):
    global maxCache
    while n > maxCache:
	maxCache = caches.next()
	pentCache.add(maxCache)
    return n in pentCache

for delta in deltas:
    (this, after) = itertools.tee(pentagons(), 2)
    after.next()
    for (pj, pj_1) in itertools.izip(this, after):
	pk = pj + delta
	if pk < pj_1:
	    break
	elif isPent(pk) and isPent(pk + pj):
	    print delta
	    sys.exit()
    print 'Not %d' % (delta,)  #####
