#!/usr/bin/python
"""Triangular, pentagonal, and hexagonal

   Triangle, pentagonal, and hexagonal numbers are generated by the following
   formulae:

       Triangle    $T_n = n(n+1)/2$   1, 3, 6, 10, 15, ...
       Pentagonal  $P_n = n(3n-1)/2$  1, 5, 12, 22, 35, ...
       Hexagonal   $H_n = n(2n-1)$    1, 6, 15, 28, 45, ...

   It can be verified that $T_{285} = P_{165} = H_{143} = 40755$.

   Find the next triangle number that is also pentagonal and hexagonal."""

from itertools import imap, count

__tags__ = ['integer sequences', 'triangle numbers', 'pentagonal numbers',
            'hexagonal numbers']

def solve():
    T = imap(lambda n: n*(n+1) // 2, count(286))
    P = imap(lambda n: n*(3*n-1) // 2, count(166))
    H = imap(lambda n: n*(2*n-1), count(144))

    t = next(T)
    p = next(P)
    h = next(H)

    while not (t == p == h):
        while t < p or t < h:
            t = next(T)
        while p < t or p < h:
            p = next(P)
        while h < t or h < p:
            h = next(H)
    return t

if __name__ == '__main__':
    print solve()
